//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace Roadie.Library.Models.ThirdPartyApi.Subsonic
{
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
    [System.Xml.Serialization.XmlRootAttribute("subsonic-response", Namespace = "http://subsonic.org/restapi", IsNullable = false)]
    public partial class Response
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("album", typeof(AlbumWithSongsID3))]
        [System.Xml.Serialization.XmlElementAttribute("albumInfo", typeof(AlbumInfo))]
        [System.Xml.Serialization.XmlElementAttribute("albumList", typeof(AlbumList))]
        [System.Xml.Serialization.XmlElementAttribute("albumList2", typeof(AlbumList2))]
        [System.Xml.Serialization.XmlElementAttribute("artist", typeof(ArtistWithAlbumsID3))]
        [System.Xml.Serialization.XmlElementAttribute("artistInfo", typeof(ArtistInfo))]
        [System.Xml.Serialization.XmlElementAttribute("artistInfo2", typeof(ArtistInfo2))]
        [System.Xml.Serialization.XmlElementAttribute("artists", typeof(ArtistsID3))]
        [System.Xml.Serialization.XmlElementAttribute("bookmarks", typeof(Bookmarks))]
        [System.Xml.Serialization.XmlElementAttribute("chatMessages", typeof(ChatMessages))]
        [System.Xml.Serialization.XmlElementAttribute("directory", typeof(Directory))]
        [System.Xml.Serialization.XmlElementAttribute("error", typeof(Error))]
        [System.Xml.Serialization.XmlElementAttribute("genres", typeof(Genres))]
        [System.Xml.Serialization.XmlElementAttribute("indexes", typeof(Indexes))]
        [System.Xml.Serialization.XmlElementAttribute("internetRadioStations", typeof(InternetRadioStations))]
        [System.Xml.Serialization.XmlElementAttribute("jukeboxPlaylist", typeof(JukeboxPlaylist))]
        [System.Xml.Serialization.XmlElementAttribute("jukeboxStatus", typeof(JukeboxStatus))]
        [System.Xml.Serialization.XmlElementAttribute("license", typeof(License))]
        [System.Xml.Serialization.XmlElementAttribute("lyrics", typeof(Lyrics))]
        [System.Xml.Serialization.XmlElementAttribute("musicFolders", typeof(MusicFolders))]
        [System.Xml.Serialization.XmlElementAttribute("newestPodcasts", typeof(NewestPodcasts))]
        [System.Xml.Serialization.XmlElementAttribute("nowPlaying", typeof(NowPlaying))]
        [System.Xml.Serialization.XmlElementAttribute("playQueue", typeof(PlayQueue))]
        [System.Xml.Serialization.XmlElementAttribute("playlist", typeof(PlaylistWithSongs))]
        [System.Xml.Serialization.XmlElementAttribute("playlists", typeof(Playlists))]
        [System.Xml.Serialization.XmlElementAttribute("podcasts", typeof(Podcasts))]
        [System.Xml.Serialization.XmlElementAttribute("randomSongs", typeof(Songs))]
        [System.Xml.Serialization.XmlElementAttribute("scanStatus", typeof(ScanStatus))]
        [System.Xml.Serialization.XmlElementAttribute("searchResult", typeof(SearchResult))]
        [System.Xml.Serialization.XmlElementAttribute("searchResult2", typeof(SearchResult2))]
        [System.Xml.Serialization.XmlElementAttribute("searchResult3", typeof(SearchResult3))]
        [System.Xml.Serialization.XmlElementAttribute("shares", typeof(Shares))]
        [System.Xml.Serialization.XmlElementAttribute("similarSongs", typeof(SimilarSongs))]
        [System.Xml.Serialization.XmlElementAttribute("similarSongs2", typeof(SimilarSongs2))]
        [System.Xml.Serialization.XmlElementAttribute("song", typeof(Child))]
        [System.Xml.Serialization.XmlElementAttribute("songsByGenre", typeof(Songs))]
        [System.Xml.Serialization.XmlElementAttribute("starred", typeof(Starred))]
        [System.Xml.Serialization.XmlElementAttribute("starred2", typeof(Starred2))]
        [System.Xml.Serialization.XmlElementAttribute("topSongs", typeof(TopSongs))]
        [System.Xml.Serialization.XmlElementAttribute("user", typeof(User))]
        [System.Xml.Serialization.XmlElementAttribute("users", typeof(Users))]
        [System.Xml.Serialization.XmlElementAttribute("videoInfo", typeof(VideoInfo))]
        [System.Xml.Serialization.XmlElementAttribute("videos", typeof(Videos))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ResponseStatus status;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
    public partial class AlbumWithSongsID3 : AlbumID3
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("song")]
        public Child[] song;
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PodcastEpisode))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NowPlayingEntry))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
    public partial class Child
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string parent;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isDir;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string title;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string album;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string artist;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int track;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool trackSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int year;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool yearSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string genre;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string coverArt;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int size;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sizeSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string contentType;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string suffix;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string transcodedContentType;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string transcodedSuffix;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int duration;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool durationSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int bitRate;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bitRateSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string path;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isVideo;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isVideoSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int userRating;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool userRatingSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short averageRating;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool averageRatingSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int playCount;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool playCountSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int discNumber;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool discNumberSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime created;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool createdSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime? starred;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool starredSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string albumId;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string artistId;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public MediaType type;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long bookmarkPosition;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bookmarkPositionSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int originalWidth;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool originalWidthSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int originalHeight;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool originalHeightSpecified;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
    public enum MediaType
    {

        /// <remarks/>
        music,

        /// <remarks/>
        podcast,

        /// <remarks/>
        audiobook,

        /// <remarks/>
        video,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
    public partial class Error
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int code;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string message;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
    public partial class ScanStatus
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool scanning;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long count;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool countSpecified;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
    public partial class TopSongs
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("song")]
        public Child[] song;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
    public partial class SimilarSongs2
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("song")]
        public Child[] song;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
    public partial class SimilarSongs
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("song")]
        public Child[] song;
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ArtistInfo2))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ArtistInfo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
    public partial class ArtistInfoBase
    {

        /// <remarks/>
        public string biography;

        /// <remarks/>
        public string musicBrainzId;

        /// <remarks/>
        public string lastFmUrl;

        /// <remarks/>
        public string smallImageUrl;

        /// <remarks/>
        public string mediumImageUrl;

        /// <remarks/>
        public string largeImageUrl;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
    public partial class ArtistInfo2 : ArtistInfoBase
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("similarArtist")]
        public ArtistID3[] similarArtist;
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ArtistWithAlbumsID3))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
    public partial class ArtistID3
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string coverArt;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string artistImageUrl;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int albumCount;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime starred;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool starredSpecified;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
    public partial class ArtistWithAlbumsID3 : ArtistID3
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("album")]
        public AlbumID3[] album;
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AlbumWithSongsID3))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
    public partial class AlbumID3
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string artist;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string artistId;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string coverArt;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int songCount;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int duration;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long playCount;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool playCountSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime created;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime starred;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool starredSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int year;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool yearSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string genre;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
    public partial class ArtistInfo : ArtistInfoBase
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("similarArtist")]
        public Artist[] similarArtist;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
    public partial class Artist
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string artistImageUrl;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime starred;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool starredSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int userRating;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool userRatingSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double averageRating;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool averageRatingSpecified;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
    public partial class AlbumInfo
    {

        /// <remarks/>
        public string notes;

        /// <remarks/>
        public string musicBrainzId;

        /// <remarks/>
        public string lastFmUrl;

        /// <remarks/>
        public string smallImageUrl;

        /// <remarks/>
        public string mediumImageUrl;

        /// <remarks/>
        public string largeImageUrl;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
    public partial class Starred2
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("artist")]
        public ArtistID3[] artist;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("album")]
        public AlbumID3[] album;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("song")]
        public Child[] song;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
    public partial class Starred
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("artist")]
        public Artist[] artist;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("album")]
        public Child[] album;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("song")]
        public Child[] song;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
    public partial class Shares
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("share")]
        public Share[] share;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
    public partial class Share
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("entry")]
        public Child[] entry;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string url;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string username;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime created;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime expires;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool expiresSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime lastVisited;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lastVisitedSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int visitCount;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
    public partial class PlayQueue
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("entry")]
        public Child[] entry;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int current;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool currentSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long position;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool positionSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string username;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime changed;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string changedBy;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
    public partial class Bookmarks
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("bookmark")]
        public Bookmark[] bookmark;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
    public partial class Bookmark
    {

        /// <remarks/>
        public Child entry;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long position;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string username;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string comment;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime created;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime changed;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
    public partial class InternetRadioStations
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("internetRadioStation")]
        public InternetRadioStation[] internetRadioStation;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
    public partial class InternetRadioStation
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string streamUrl;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string homePageUrl;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
    public partial class NewestPodcasts
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("episode")]
        public PodcastEpisode[] episode;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
    public partial class PodcastEpisode : Child
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string streamId;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string channelId;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PodcastStatus status;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime publishDate;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool publishDateSpecified;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
    public enum PodcastStatus
    {

        /// <remarks/>
        @new,

        /// <remarks/>
        downloading,

        /// <remarks/>
        completed,

        /// <remarks/>
        error,

        /// <remarks/>
        deleted,

        /// <remarks/>
        skipped,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
    public partial class Podcasts
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("channel")]
        public PodcastChannel[] channel;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
    public partial class PodcastChannel
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("episode")]
        public PodcastEpisode[] episode;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string url;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string title;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string coverArt;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string originalImageUrl;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PodcastStatus status;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string errorMessage;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
    public partial class Lyrics
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string artist;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string title;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
    public partial class Songs
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("song")]
        public Child[] song;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
    public partial class AlbumList2
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("album")]
        public AlbumID3[] album;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
    public partial class AlbumList
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("album")]
        public Child[] album;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
    public partial class ChatMessages
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("chatMessage")]
        public ChatMessage[] chatMessage;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
    public partial class ChatMessage
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string username;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long time;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string message;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
    public partial class Users
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("user")]
        public User[] user;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
    public partial class User
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("folder")]
        public int[] folder;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string username;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string email;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool scrobblingEnabled;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int maxBitRate;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxBitRateSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool adminRole;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool settingsRole;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool downloadRole;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool uploadRole;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool playlistRole;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool coverArtRole;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool commentRole;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool podcastRole;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool streamRole;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool jukeboxRole;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool shareRole;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool videoConversionRole;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime avatarLastChanged;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool avatarLastChangedSpecified;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
    public partial class License
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool valid;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string email;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime licenseExpires;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool licenseExpiresSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime trialExpires;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool trialExpiresSpecified;
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(JukeboxPlaylist))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
    public partial class JukeboxStatus
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int currentIndex;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool playing;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float gain;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int position;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool positionSpecified;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
    public partial class JukeboxPlaylist : JukeboxStatus
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("entry")]
        public Child[] entry;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
    public partial class Playlists
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("playlist")]
        public Playlist[] playlist;
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PlaylistWithSongs))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
    public partial class Playlist
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("allowedUser")]
        public string[] allowedUser;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string comment;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string owner;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool @public;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool publicSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int songCount;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int duration;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime created;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime changed;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string coverArt;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
    public partial class PlaylistWithSongs : Playlist
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("entry")]
        public Child[] entry;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
    public partial class SearchResult3
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("artist")]
        public ArtistID3[] artist;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("album")]
        public AlbumID3[] album;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("song")]
        public Child[] song;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
    public partial class SearchResult2
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("artist")]
        public Artist[] artist;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("album")]
        public Child[] album;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("song")]
        public Child[] song;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
    public partial class SearchResult
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("match")]
        public Child[] match;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int offset;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int totalHits;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
    public partial class NowPlaying
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("entry")]
        public NowPlayingEntry[] entry;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
    public partial class NowPlayingEntry : Child
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string username;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int minutesAgo;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int playerId;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string playerName;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
    public partial class VideoConversion
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int bitRate;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bitRateSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int audioTrackId;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool audioTrackIdSpecified;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
    public partial class AudioTrack
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string languageCode;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
    public partial class Captions
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
    public partial class VideoInfo
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("captions")]
        public Captions[] captions;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("audioTrack")]
        public AudioTrack[] audioTrack;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("conversion")]
        public VideoConversion[] conversion;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
    public partial class Videos
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("video")]
        public Child[] video;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
    public partial class IndexID3
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("artist")]
        public ArtistID3[] artist;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
    public partial class ArtistsID3
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("index")]
        public IndexID3[] index;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ignoredArticles;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
    public partial class Genres
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("genre")]
        public Genre[] genre;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
    public partial class Genre
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int songCount;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int albumCount;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string value;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
    public partial class Directory
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("child")]
        public Child[] child;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string parent;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime? starred;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool starredSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int userRating;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool userRatingSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short averageRating;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool averageRatingSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long playCount;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool playCountSpecified;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
    public partial class Index
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("artist")]
        public Artist[] artist;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
    public partial class Indexes
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("shortcut")]
        public Artist[] shortcut;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("index")]
        public Index[] index;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("child")]
        public Child[] child;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long lastModified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ignoredArticles;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
    public partial class MusicFolders
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("musicFolder")]
        public MusicFolder[] musicFolder;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
    public partial class MusicFolder
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int id;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi", IncludeInSchema = false)]
    public enum ItemChoiceType
    {

        /// <remarks/>
        album,

        /// <remarks/>
        albumInfo,

        /// <remarks/>
        albumList,

        /// <remarks/>
        albumList2,

        /// <remarks/>
        artist,

        /// <remarks/>
        artistInfo,

        /// <remarks/>
        artistInfo2,

        /// <remarks/>
        artists,

        /// <remarks/>
        bookmarks,

        /// <remarks/>
        chatMessages,

        /// <remarks/>
        directory,

        /// <remarks/>
        error,

        /// <remarks/>
        genres,

        /// <remarks/>
        indexes,

        /// <remarks/>
        internetRadioStations,

        /// <remarks/>
        jukeboxPlaylist,

        /// <remarks/>
        jukeboxStatus,

        /// <remarks/>
        license,

        /// <remarks/>
        lyrics,

        /// <remarks/>
        musicFolders,

        /// <remarks/>
        newestPodcasts,

        /// <remarks/>
        nowPlaying,

        /// <remarks/>
        playQueue,

        /// <remarks/>
        playlist,

        /// <remarks/>
        playlists,

        /// <remarks/>
        podcasts,

        /// <remarks/>
        randomSongs,

        /// <remarks/>
        scanStatus,

        /// <remarks/>
        searchResult,

        /// <remarks/>
        searchResult2,

        /// <remarks/>
        searchResult3,

        /// <remarks/>
        shares,

        /// <remarks/>
        similarSongs,

        /// <remarks/>
        similarSongs2,

        /// <remarks/>
        song,

        /// <remarks/>
        songsByGenre,

        /// <remarks/>
        starred,

        /// <remarks/>
        starred2,

        /// <remarks/>
        topSongs,

        /// <remarks/>
        user,

        /// <remarks/>
        users,

        /// <remarks/>
        videoInfo,

        /// <remarks/>
        videos,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
    public enum ResponseStatus
    {

        /// <remarks/>
        ok,

        /// <remarks/>
        failed,
    }
}
